# wordpress-pvc.yml
# ============================================
# PersistentVolumeClaim (PVC) para WordPress
# ============================================
# Este YAML crea un PersistentVolumeClaim (PVC) para solicitar
# almacenamiento de 5Gi para la aplicaci칩n WordPress.
# El volumen tendr치 acceso "ReadWriteOnce" y usar치 la clase
# de almacenamiento "default".
# ============================================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # El tama침o de almacenamiento solicitado
  storageClassName: default
